
import com.mysql.jdbc.Connection;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.io.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Admin
 */
public class Teacher extends javax.swing.JFrame {
    DBConnection db=null;
    PreparedStatement pst=null,pst1;
    ResultSet rs=null,rs1;
    java.sql.Connection con = null;
    JLabel exno,queno,QT,op1,op2,op3,op4,ans,queno1,QT1,op11,op21,op31,op41,ans1,exnm,noque,examid,namelabel,sublabel,namelabel1,uname,nm,sub,subhd,l1,l2,setmarks;
    JTextField exf,qnof,qtf,op1f,op2f,op3f,op4f,ansf,qnof1,qtf1,op1f1,op2f1,op3f1,op4f1,ansf1,exid,examnm,unametf,nmtf,subtf,newsub,setmarktf;
    JButton addb,editb,saveb,submitb,editque,deleteque,go,export,addSub,editsub,deletesub;
    JComboBox Combobox_name,examlist,examlist1,Combo1,combo2,semlist;
    JTable table;
    String selectedValue,selectedValue1,value,value1,labelvalue,c1,c2,c3,c4,c5,c6,c7,c8,combo2value;
    JScrollPane jp;
    int sem_value;
    public Teacher() {
        initComponents();
        namelabel=new JLabel();
        namelabel.setBounds(34,82,148,27);
        namelabel.setFont(new Font("Tahoma",Font.BOLD,24));
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel.add(namelabel);
        sublabel=new JLabel();
        sublabel.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        sublabel.setForeground(new java.awt.Color(255, 255, 255));
        sublabel.setBounds(34,119,500,37);
        jPanel.add(sublabel);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        setExam = new javax.swing.JButton();
        Showexamlist = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        myAccount = new javax.swing.JButton();
        ShowResult = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1632, 918));
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(102, 0, 102));

        setExam.setBackground(new java.awt.Color(102, 0, 102));
        setExam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        setExam.setForeground(new java.awt.Color(255, 255, 255));
        setExam.setText("Set Exam");
        setExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setExamActionPerformed(evt);
            }
        });

        Showexamlist.setBackground(new java.awt.Color(102, 0, 102));
        Showexamlist.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Showexamlist.setForeground(new java.awt.Color(255, 255, 255));
        Showexamlist.setText("Show exam list");
        Showexamlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowexamlistActionPerformed(evt);
            }
        });

        LogOut.setBackground(new java.awt.Color(102, 0, 102));
        LogOut.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        myAccount.setBackground(new java.awt.Color(102, 0, 102));
        myAccount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        myAccount.setForeground(new java.awt.Color(255, 255, 255));
        myAccount.setText("Manage Subjects");
        myAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAccountActionPerformed(evt);
            }
        });

        ShowResult.setBackground(new java.awt.Color(102, 0, 102));
        ShowResult.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ShowResult.setForeground(new java.awt.Color(255, 255, 255));
        ShowResult.setText("Show Result");
        ShowResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap(582, Short.MAX_VALUE)
                .addComponent(myAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(setExam, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Showexamlist, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ShowResult, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setExam, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Showexamlist, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowResult, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1268, 1268, 1268))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(658, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private  void Combo1ActionPerformed(ActionEvent evt){
        String subcode=(String) Combo1.getSelectedItem();
        String subName = null;
        String semester = null;
        newsub.setText(subcode);
         db=new DBConnection();
        Connection con;
        try {            
            con=db.CONN();           
            //labelvalue=namelabel.getText();       
            pst=con.prepareStatement("Select name,sem from subject where sub_code=?" );
            pst.setString(1,subcode);
            rs=pst.executeQuery();
            if(rs.next()){
                subName=rs.getString("name");
                semester = rs.getString("sem");
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
        nmtf.setText(subName);
        unametf.setText(semester);
   }
    private void myAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccountActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        unametf=new JTextField();
        nmtf=new JTextField(); 
        newsub=new JTextField();
        uname=new JLabel();
        nm=new JLabel();
        sub=new JLabel();
        //subhd=new JLabel();
        l1=new JLabel();
        l2=new JLabel();
        
        sub.setBounds(100,70,195,22);
        sub.setBackground(new java.awt.Color(204, 204, 204));
        sub.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sub.setForeground(new java.awt.Color(102, 0, 102));
        sub.setText("Subjects handling :");
        Combo1 = new JComboBox();
        Combo1.setBounds(150,100,300,70); 
        Combo1.setFont(new Font("Tahoma",Font.BOLD,20));
        Fillcombo1(Combo1);
         jPanel3.add(Combo1);
         Combo1.addActionListener(this::Combo1ActionPerformed);
       /* subhd.setBounds(150,100,376,70);
        subhd.setFont(new Font("Tahoma",0,18));
        subhd.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        l1.setBounds(120,250,500,20);
        l1.setFont(new Font("Tahoma",0,18));
        l1.setText("Add a new Subject :");
        //l1.setBorder(new EmptyBorder);*/
        uname.setBounds(550,300,120,22);
        uname.setBackground(new java.awt.Color(204, 204, 204));
        uname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uname.setForeground(new java.awt.Color(102, 0, 102));
        uname.setText("Subject code:");
         newsub.setBounds(761,295,200,50);
        newsub.setFont(new Font("Tahoma",0,18));
        newsub.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        //newsub.setText("sub code");
        nm.setBounds(550,405,140,22);
        nm.setText("Name of Subject:");
        nm.setForeground(new java.awt.Color(102, 0, 102));
        nm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nmtf.setBounds(761,400,200,50);
        nmtf.setFont(new Font("Tahoma",0,18));
        //nmtf.setText("sub name");

        nmtf.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        unametf.setBounds(761,500,200,50);
        unametf.setFont(new Font("Tahoma",0,18));
        //unametf.setText("semester");
        unametf.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        l2.setBounds(550,508,120,22);
        l2.setText("For semester:");
        l2.setForeground(new Color(102, 0, 102));
        l2.setFont(new Font("Tahoma", 0, 18)); // 
        addSub=new JButton();
        addSub.setBounds(691,600,200,50);
        addSub.setText("Add Subject");
        addSub.setForeground(Color.WHITE);
        addSub.setBackground(new Color(102, 0, 102));
        addSub.setFont(new Font("Tahoma", 1, 16));
        editsub=new JButton();
        editsub.setBounds(471,600,200,50);
        editsub.setText("Edit Subject");
        editsub.setForeground(Color.WHITE);
        editsub.setBackground(new Color(102, 0, 102));
        editsub.setFont(new Font("Tahoma", 1, 16));
        deletesub=new JButton();
        deletesub.setBounds(911,600,200,50);
        deletesub.setText("Delete");
        deletesub.setForeground(Color.WHITE);
        deletesub.setFont(new Font("Tahoma", 1, 16));
        deletesub.setBackground(new Color(102, 0, 102));
        jPanel3.add(uname);   
        jPanel3.add(unametf); 
        jPanel3.add(nm);
        jPanel3.add(nmtf);  
        //jPanel3.add(subhd);  
        jPanel3.add(newsub);  
        jPanel3.add(sub);  
        jPanel3.add(l1);
        jPanel3.add(l2);
        jPanel3.add(addSub);
        jPanel3.add(editsub);
        jPanel3.add(deletesub);  
        addSub.addActionListener(this::addSubActionPerformed);
        editsub.addActionListener(this::editsubActionPerformed);
        deletesub.addActionListener(this::deletesubActionPerformed);
    }//GEN-LAST:event_myAccountActionPerformed
    private void addSubActionPerformed(java.awt.event.ActionEvent evt) { 
         db=new DBConnection();
         Connection con;
        try {
            con=db.CONN();
            pst=con.prepareStatement("Insert into subject values(?,?,?,?)");
            pst.setString(1,newsub.getText());
            pst.setString(2,nmtf.getText());
            pst.setString(3,unametf.getText());
            pst.setString(4,namelabel.getText());
            int i=pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inserted "+i+" row");  
            if(i==1){
                sublabel.setText((sublabel.getText())+","+newsub.getText());
            }
             Combo1.addItem(newsub.getText());
            // Fillcombo1(Combo1);
             nmtf.setText("");
             unametf.setText("");
             newsub.setText("");
            
        }      
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }         
    } 
    private void editsubActionPerformed(java.awt.event.ActionEvent evt) {
         db=new DBConnection();
        Connection con;
        try {
            con=db.CONN();
            pst=con.prepareStatement("Update subject set name=?,sem=? where sub_code=? and staff_id=?");
            pst.setString(1,nmtf.getText());
            pst.setString(2,unametf.getText());
            pst.setString(3,newsub.getText());
             pst.setString(4,namelabel.getText());
            int i=pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Edited "+i+" row");  
             nmtf.setText("");
             unametf.setText("");
             newsub.setText("");
             //Fillcombo1(Combo1);
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        } 
        
     }
     private void deletesubActionPerformed(java.awt.event.ActionEvent evt) {
        int response=JOptionPane.showConfirmDialog(this, "Do you want to delete this record?", "Confirm", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            db=new DBConnection();
            Connection con;
            try {
                con=db.CONN();
                pst=con.prepareStatement("delete from subject where sub_code=? and staff_id=?");
                 pst.setString(1,newsub.getText());
                pst.setString(2,namelabel.getText());
                int i=pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Deleted "+i+" row"); 
                Combo1.removeItem(newsub.getText());
                nmtf.setText("");
                 unametf.setText("");
                 newsub.setText("");
                 
                 sublabel.setText("Subject handling:");
                 pst1=con.prepareStatement("select sub_code from subject where staff_id=?");
                 pst1.setString(1,namelabel.getText());
                rs1=pst1.executeQuery();
                while(rs1.next()){
                    sublabel.setText((sublabel.getText())+", "+rs1.getString(1));
                }
             }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            } 
          
        }
     }
    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        Homepage.main(null);
        dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void setExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setExamActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
 
        examid=new JLabel();
        exnm=new JLabel();
        examid.setText("Subject code");
        examid.setFont(new Font("Tahoma",Font.BOLD,16));
        examid.setBounds(131,93,150,48);
        exnm.setText("Exam Name");
        exnm.setFont(new Font("Tahoma",Font.BOLD,16));
        exnm.setBounds(131,163,150,48);
         Combobox_name = new JComboBox();
        Combobox_name.setBounds(300,93,150,48); 
        Combobox_name.setFont(new Font("Tahoma",Font.BOLD,16));
        Fillcombo1(Combobox_name);
         jPanel3.add(Combobox_name);
        combo2=new JComboBox();
        combo2.setBounds(300,163,150,48); 
        combo2.setFont(new Font("Tahoma",Font.BOLD,16));
        combo2.setModel(new DefaultComboBoxModel(new String[] { "IA1", "IA2", "IA3" }));
        jPanel3.add(examid);
        jPanel3.add(exnm);   
        jPanel3.add(combo2);
        submitb=new JButton();
        submitb.setText("Go");
        submitb.setFont(new Font("Tahoma",Font.BOLD,16));
        submitb.setForeground(Color.WHITE);
        submitb.setBackground(new Color(102, 0, 102));
        submitb.setBounds(200,340,114,48);
        jPanel3.add(submitb);
        Combobox_name.addActionListener(this::Combobox_nameActionPerformed); 
         combo2.addActionListener(this::combo2ActionPerformed); 
        submitb.addActionListener(this::submitbActionPerformed);
    }//GEN-LAST:event_setExamActionPerformed

    private void submitbActionPerformed(java.awt.event.ActionEvent evt){
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();   
         op1=new JLabel();
        op2=new JLabel();
        op3=new JLabel();
        op4=new JLabel();
        ans=new JLabel();
        qtf=new JTextField();
        op1f=new JTextField();
        op2f=new JTextField();
        op3f=new JTextField();
        op4f=new JTextField();
        ansf=new JTextField();
        queno=new JLabel();
        qnof=new JTextField();
        queno.setText("Q.no:");
        queno.setBounds(18,23,50,22);
        queno.setFont(new Font("Tahoma",Font.BOLD,16));
        queno.setForeground(new Color(102, 0, 102));      
        qnof.setBounds(18,43,61,50);   
        qnof.setFont(new Font("Calibiri",Font.BOLD,16));     
        qnof.setForeground(new Color(102, 0, 102));
        qnof.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        jPanel3.add(queno);
        jPanel3.add(qnof);
        setmarks=new JLabel();
        setmarktf=new JTextField();

        setmarks.setText("Marks:");
        setmarks.setBounds(1500,23,90,22);
        setmarks.setFont(new Font("Tahoma",Font.BOLD,16));
        setmarks.setForeground(new Color(102, 0, 102));
       
        setmarktf.setBounds(1500,43,61,50);   
        setmarktf.setFont(new Font("Calibiri",Font.BOLD,16));     
        setmarktf.setForeground(new Color(102, 0, 102));
        setmarktf.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        jPanel3.add(setmarktf);
        jPanel3.add(setmarks);
        op1.setText("Option 1");
        op1.setBounds(217,258,81,22);
        op1.setFont(new Font("Tahoma",0,18));
        op1.setForeground(new Color(102, 0, 102));
        op2.setText("Option 2");
        op2.setBounds(217,346,81,22);
        op2.setFont(new Font("Tahoma",0,18));
        op2.setForeground(new Color(102, 0, 102));
        op3.setText("Option 3");
        op3.setBounds(217,433,81,22);
        op3.setFont(new Font("Tahoma",0,18));
        op3.setForeground(new Color(102, 0, 102));
        op4.setText("Option 4");
        op4.setBounds(217,520,81,22);
        op4.setFont(new Font("Tahoma",0,18));
        op4.setForeground(new Color(102, 0, 102));
        ans.setText("Answer");
        ans.setBounds(217,607,81,22);
        ans.setFont(new Font("Tahoma",0,18));
        ans.setForeground(new Color(102, 0, 102));
        
        qtf.setBounds(101,43,1390,181);
        qtf.setFont(new Font("Tahoma",0,18));
        qtf.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        op1f.setBounds(361,234,952,77);
        op1f.setFont(new Font("Tahoma",0,18));
        op1f.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        op2f.setBounds(361,321,952,77);
        op2f.setFont(new Font("Tahoma",0,18));
        op2f.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        op3f.setBounds(361,408,952,77);
        op3f.setFont(new Font("Tahoma",0,18));
        op3f.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        op4f.setBounds(361,495,952,77);
        op4f.setFont(new Font("Tahoma",0,18));
        op4f.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        ansf.setBounds(361,582,952,77);
        ansf.setFont(new Font("Tahoma",0,18));
        ansf.setBorder(BorderFactory.createCompoundBorder(new SoftBevelBorder(BevelBorder.RAISED), BorderFactory.createEtchedBorder()));
        //jPanel3.add(QT);
        jPanel3.add(qtf);
        jPanel3.add(ans);
        jPanel3.add(ansf);
        jPanel3.add(op1);
        jPanel3.add(op2);
        jPanel3.add(op3);
        jPanel3.add(op4);
        jPanel3.add(op1f);
        jPanel3.add(op2f);
        jPanel3.add(op3f);
        jPanel3.add(op4f);
        addb=new JButton();
        addb.setText("Add Question");
        addb.setFont(new Font("Tahoma",Font.BOLD,16));
        addb.setBackground(new Color(102, 0, 102));
        addb.setForeground(new Color(255, 255, 255));
        addb.setBounds(1385,630,170,45);
        jPanel3.add(addb);
        addb.addActionListener(this::addbActionPerformed);
        //fillpanel();
        
    }
    private  void Combobox_nameActionPerformed(ActionEvent evt){
         selectedValue =Combobox_name.getSelectedItem().toString();      
    }
    private  void combo2ActionPerformed(ActionEvent evt){
          combo2value =combo2.getSelectedItem().toString();      
    }
    private void addbActionPerformed(java.awt.event.ActionEvent evt) { 
         db=new DBConnection();
        Connection con;
        try {
            con=db.CONN();
            pst=con.prepareStatement("Insert into questions values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,qnof.getText());
            pst.setString(2,qtf.getText());
            pst.setString(3,op1f.getText());
            pst.setString(4,op2f.getText());
            pst.setString(5,op3f.getText());
            pst.setString(6,op4f.getText());
            pst.setString(7,ansf.getText());
            pst.setString(8,setmarktf.getText());
            pst.setString(9,selectedValue);
            pst.setString(10,combo2value);
            int j=pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inserted "+j+" row");
            qnof.setText("");
            qtf.setText("");
            op1f.setText("");
            op2f.setText("");
            op3f.setText("");
            op4f.setText("");
            ansf.setText(""); 
            setmarktf.setText("");
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
    } 
     
    private void ShowexamlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowexamlistActionPerformed
        // TODO add your handling code here 
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();  
        examlist=new JComboBox();
        namelabel1=new JLabel();
        examlist.setBounds(400,60,340,48);
        examlist.setFont(new java.awt.Font("Tahoma", 0, 18));
        
        namelabel1.setBounds(280,60,150,40);
        namelabel1.setText("Select Exam id");
        namelabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        namelabel1.setForeground(new Color(102,0,102));
        combo2=new JComboBox();
        combo2.setBounds(760,60,90,48); 
        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"IA1", "IA2", "IA3"}));
        combo2.setFont(new Font("Tahoma",Font.BOLD,18));
        go=new JButton();
        go.setText("Go");
        go.setFont(new Font("Tahoma",Font.BOLD,16));
        go.setBounds(870,60,100,48);
        go.addActionListener(this::goActionPerformed);
        jPanel3.add(go);
        jPanel3.add(combo2);
        jPanel3.add(namelabel1);
        jPanel3.add(examlist);
        Fillcombo1(examlist);
        examlist.addActionListener(this::examlistActionPerformed);
         combo2.addActionListener(this::combo2ActionPerformed);
        
         editque=new JButton();
        editque.setText("Edit");
        editque.setFont(new Font("Tahoma",Font.BOLD,16));
        editque.setBounds(200,500,200,45);
         jPanel3.add(editque);
   
        deleteque=new JButton();
        deleteque.setText("delete");
        deleteque.setFont(new Font("Tahoma",Font.BOLD,16));
        deleteque.setBounds(430,500,200,45);
         jPanel3.add(deleteque);
        deleteque.setVisible(false);
        export=new JButton();
        export.setText("Export");
        export.setFont(new Font("Tahoma",Font.BOLD,16));
        export.setBounds(660,500,200,45);
         jPanel3.add(export);
        export.setVisible(false);
        editque.setVisible(false);
         jp=new JScrollPane();
         jp.setBounds(50,200,1550,270);
         jPanel3.add(jp);
         table=new JTable();
         jp.setViewportView(table);
         table.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,18));
        table.setRowHeight(35);
        table.setFont(new java.awt.Font("Tahoma", 0, 18)); 
          table.setVisible(false);
          jp.setVisible(false);
         deleteque.addActionListener(this::deletequeActionPerformed);
         export.addActionListener(this::exportActionPerformed);
        editque.addActionListener(this::editqueActionPerformed);
    }//GEN-LAST:event_ShowexamlistActionPerformed

    private void ShowResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowResultActionPerformed
        // TODO add your handling code here:
         jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate(); 
        JLabel exam,sem;
        JButton sembutton;
        sem=new JLabel();
        exam=new JLabel();
        
        exam.setText("Subjectwise IA marks:");
        exam.setBounds(157,60,180,40);
        exam.setFont(new Font("Tahoma",0,18));
        sem.setText("Select Semester:");
        sem.setBounds(1070,60,150,40);
        sem.setFont(new Font("Tahoma",0,18));
       
        examlist1=new JComboBox(); 
        semlist=new JComboBox();
        examlist1.setBounds(340,60,200,40);
        examlist1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jPanel3.add(examlist1);
        semlist.setBounds(1225,60,200,40);
        semlist.setFont(new java.awt.Font("Tahoma", 0, 18));
        jPanel3.add(semlist);
        
        jPanel3.add(exam);
        jPanel3.add(sem);
        Fillcombo1(examlist1);
        fillsemlist();
       // semlist.setModel(new DefaultComboBoxModel<>(new Integer[] { 1,2,3,4,5,6,7,8}));
        examlist1.addActionListener(this::examlist1ActionPerformed);
        semlist.addActionListener(this::semlistActionPerformed);
        JButton button = new JButton();
        button.setText(">>");
        button.setFont(new Font("Tahoma",0,16));
        button.setForeground(new Color(102,0,102));
        button.setBounds(550,60,60,40);
         jPanel3.add(button);
         export=new JButton();
        export.setText("Export");
        export.setFont(new Font("Tahoma",Font.BOLD,16));
        export.setBackground(new Color(102,0,102));
        export.setForeground(Color.WHITE);
        export.setBounds(1185,600,200,48);
         jPanel3.add(export);
        export.setVisible(false);
         button.addActionListener(this::buttonActionPerformed);
          export.addActionListener(this::exportActionPerformed);
         sembutton=new JButton();
        sembutton.setText(">>");
        sembutton.setFont(new Font("Tahoma",0,16));
        sembutton.setBounds(1430,60,60,40);
         jPanel3.add(sembutton);
         sembutton.addActionListener(this::sembuttonActionPerformed);
         jp=new JScrollPane();
        jp.setBounds(10,200,1590,270);
        jPanel3.add(jp);
        table=new JTable();
        jp.setViewportView(table);
        table.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,18));
        table.setRowHeight(30);
        table.setFont(new java.awt.Font("Tahoma", 0, 18));
        jp.setVisible(false);
        table.setVisible(false);
    }//GEN-LAST:event_ShowResultActionPerformed
    private  void sembuttonActionPerformed(ActionEvent evt){
          jp.setVisible(true);
         table.setVisible(true);
         export.setVisible(true);
         db=new DBConnection();
        try {
            con=db.CONN();
            //String sql=;
            pst=con.prepareCall("call MARKSHEET(?)");
            pst.setInt(1,sem_value);
            rs=pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));  
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private  void semlistActionPerformed(ActionEvent evt){
         sem_value=(int) semlist.getSelectedItem();
    }
    private  void buttonActionPerformed(ActionEvent evt){
        jp.setVisible(true);
        table.setVisible(true);
        export.setVisible(true);
        //Update_Table(); 
         db=new DBConnection();
        try {
            con=db.CONN();
            //String sql=;
            pst=con.prepareCall("call showResult(?)");
            pst.setString(1,value1);
            rs=pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private  void examlist1ActionPerformed(java.awt.event.ActionEvent evt){
        value1 =examlist1.getSelectedItem().toString();     
    }
    private void exportActionPerformed(ActionEvent evt){
        File file = null;
        try{
            JFileChooser filechooser=new JFileChooser();
            int retval=filechooser.showSaveDialog(export);
            if(retval==JFileChooser.APPROVE_OPTION){
                file=filechooser.getSelectedFile();
                if(file!=null){
                    if(!file.getName().toLowerCase().endsWith(".xls")){
                        file=new File(file.getParentFile(),file.getName()+".xls");
                    }
                } 
                JOptionPane.showMessageDialog(this,"Data exported successfully!!");
            }            
            toExcel(table,file);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }       
    }
    public void toExcel(JTable table,File file) throws IOException{
        TableModel model=table.getModel();
        FileWriter excel=new FileWriter(file);
        for(int i=0;i<model.getColumnCount();i++){
            excel.write(model.getColumnName(i)+"\t");
        }
        excel.write("\n");
        for(int i=0;i<model.getRowCount();i++){
            for(int j=0;j<model.getColumnCount();j++){
                excel.write(model.getValueAt(i,j)+"\t");
            } 
            excel.write("\n");
        }
        excel.close();
    } 
    private  void examlistActionPerformed(java.awt.event.ActionEvent evt){
          value =examlist.getSelectedItem().toString();      
    }
    private  void goActionPerformed(java.awt.event.ActionEvent evt){
        deleteque.setVisible(true);
        editque.setVisible(true);
        export.setVisible(true);
        jp.setVisible(true);
        table.setVisible(true);
        Update_Table();
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
         });      
    }
    private  void editqueActionPerformed(java.awt.event.ActionEvent evt){    
        JTextField text1,text2,text3,text4,text5,anstext,marktext;
        text1=new JTextField();
        text2=new JTextField();
        text3=new JTextField();
        text4=new JTextField();
        text5=new JTextField();
        anstext=new JTextField();
        marktext=new JTextField();
        text1.setFont(new Font("Tahoma",0,18));
        text2.setFont(new Font("Tahoma",0,18));
        text3.setFont(new Font("Tahoma",0,18));
        text4.setFont(new Font("Tahoma",0,18));
        text5.setFont(new Font("Tahoma",0,18));
        anstext.setFont(new Font("Tahoma",0,18));
        text1.setText(c2);
        text2.setText(c3);
        text3.setText(c4);
        text4.setText(c5);
        text5.setText(c6);
        anstext.setText(c7);
        marktext.setText(c8);
        Object[] inputFields={"Question title",text1,"Option1",text2,"Option2",text3,"Option3",text4,"Option4",text5,"Correct answer",anstext,"Marks",marktext};
     
        int op=JOptionPane.showConfirmDialog(this, inputFields, "Save changes",JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(op==JOptionPane.OK_OPTION){
            db=new DBConnection();
             Connection con;
            try {
                con=db.CONN();
                pst=con.prepareStatement("Update questions set que_name=?,option1=?,option2=?,option3=?,option4=?,correct_ans=?,total_marks=? where sub_code=? and que_id=? and IA=?");
                pst.setString(1, text1.getText());
                pst.setString(2, text2.getText());
                pst.setString(3, text3.getText());
                pst.setString(4,text4.getText());
                pst.setString(5, text5.getText());
                pst.setString(6, anstext.getText());
                pst.setString(7, marktext.getText());
                pst.setString(8, value);
                pst.setString(9, c1);
                pst.setString(10,combo2value );
                int k=pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"updated"+k+"question");
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
        Update_Table();
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
         });
    }
    private  void deletequeActionPerformed(java.awt.event.ActionEvent evt){
        int response=JOptionPane.showConfirmDialog(this, "Do you want to delete this record?", "Confirm", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            db=new DBConnection();
            Connection con;
            try {
                con=db.CONN();
                pst=con.prepareStatement("delete from questions where sub_code=? and IA=? and que_id=?");
                pst.setString(1, value);
                 pst.setString(2,combo2value );
                pst.setString(3, c1);
                int k=pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"  deleted  "+k+"  question  ");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
         Update_Table();
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
         });
    }
    private void tableMouseClicked(MouseEvent evt) {
            try{
                int row=table.getSelectedRow();
                String rowclick=(table.getModel().getValueAt(row,0).toString());
                pst=con.prepareStatement("select *from questions  where sub_code=? and IA =? and que_id='"+rowclick+"'");
                pst.setString(1,value);
                 pst.setString(2,combo2value );
                rs=pst.executeQuery();
                if(rs.next()){
                    c1 = rs.getString("que_id");
                    c2 = rs.getString("que_name");
                    c3 = rs.getString("option1");
                    c4 = rs.getString("option2");
                    c5 = rs.getString("option3");
                    c6 = rs.getString("option4");
                    c7 = rs.getString("correct_ans"); 
                    c8 = rs.getString("total_marks");
            }    
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage()+"error table-mouse clicking");
        }
    }
    private void Update_Table(){
        db=new DBConnection();
        try{
            con=db.CONN();
            //String sql=;
            pst=con.prepareStatement("SELECT que_id as Qno,que_name as Question_title,option1 as Option_1,option2 as Option_2,option3 as Option_3,option4 as Option_4,correct_ans as answer,total_marks as marks from questions where sub_code=? and IA=?");
            pst.setString(1,value );
             pst.setString(2,combo2value );   
            rs=pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage()+"error updating table");
        }
         
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);              
            }               
        });   
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOut;
    private javax.swing.JButton ShowResult;
    private javax.swing.JButton Showexamlist;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton myAccount;
    private javax.swing.JButton setExam;
    // End of variables declaration//GEN-END:variables

    void Fillcombo1(JComboBox Combobox_name) {
         db=new DBConnection();
        Connection con;
        String sql;
        try {            
            con=db.CONN();
           // labelvalue=namelabel.getText();
            sql="Select sub_code from subject where staff_id=?";           
            pst=con.prepareStatement(sql);
            pst.setString(1,namelabel.getText());
            rs=pst.executeQuery();
            while(rs.next()){
                String name=rs.getString("sub_code");
                Combobox_name.addItem(name);
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        
    }

    private void fillsemlist() {
        db=new DBConnection();
        Connection con;
        String sql;
        try {            
            con=db.CONN();
           // labelvalue=namelabel.getText();
            sql="Select student.sem from student,score where student.Username=score.Username group by sem";           
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                int name=rs.getInt("sem");
                semlist.addItem(name);
            }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }
}